### ISSUE TITLE
Does not compile with Visual Studio 2015 and Xamarin 4.0.4.4

### ISSUE THREAD

**Issue by romankorchagin** [xamarin/Sport#15]
I get a bunch of error messages:

2>C:\Users\romeok\Desktop\Xamarin\Sport-master\Sport.iOS\Sport.iOS.App.xaml : error : Value cannot be null.
2>C:\Users\romeok\Desktop\Xamarin\Sport-master\Sport.iOS\Sport.iOS.App.xaml : error : Parameter name: method

In various .xaml files.

Opening the .xaml file in editor - IntelliSense does not help to find where the error is.

**Comment by rob-derosa** [comment]
This must be specific to your machine/config. This is not a wide-spread issue.

**Comment by mrsmitty** [comment]
We've been experiencing this issue since Xamarin Forms 2.1.0.6295
it's directly related to the [assembly: XamlCompilation(XamlCompilationOptions.Compile)] attribute on the Application.
We have the identical error message as @romankorchagin. I have noted that in this project the common code is in a Shared project. We are using a PCL.

@rob-derosa are you aware of this issue and possible work-around?

Thanks for any assistance

**Comment by rob-derosa** [comment]
No. You can try using a newer version that is compatible with the latest Azure App Services linked in the readme. If you're already using the latest version of Forms and still having issue, please submit a support ticket with the Forms team. The XamlCompilation attribute is one line of code and is used in many other Forms project, irrespective of Sport.

**Comment by brittonbeckham** [comment]
@romankorchagin did you ever determine the issue for this? I'm having the same problem and I cannot identify what is causing it.

Just so happens that today is first time trying out the XamlC feature. At first I tried the assembly level attribute in my App.cs file:

`[assembly: XamlCompilation(XamlCompilationOptions.Compile)]`

After compiling, I was getting a bunch of errors that were all identical. I also got a a different error on any page using a TemplateControl. So I pulled it off the assembly level and put a single class-level attribute on one page, and it still failed with the same error:

```
Value cannot be null.
Parameter name: method 
```
 
I poked around on Stackoverflow and found that about a year ago someone had the same issue (here), but they said they resolved it by upgrading Xam Forms to latest version. Since I'm on the latest stable versions, I have no where to go there.

I tried this class-level attribute on several pages in my app and only found it to work on a single page in my entire app... just so happens this page has zero bindings in the XAML markup. I'm wondering if a bug was introduced that causes it to blow up.

Markup of page that doesn't work:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Prepify.App.Pages.MainMenu"
                         xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"
                         BackgroundColor="White"
             Title="Menu">
    <StackLayout VerticalOptions="FillAndExpand">
        <ListView
            Header="{Binding .}"
            SeparatorColor="{StaticResource dividerColor}"
            HasUnevenRows="True"
            ItemSelected="AppMenu_OnItemSelected"
            ItemTapped="AppMenu_OnItemTapped"
            ItemsSource="{Binding Items}"
            x:Name="appMenu">

            <ListView.HeaderTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="10"/>
                            <ColumnDefinition Width="*"/>
                            <ColumnDefinition Width="30"/>
                            <ColumnDefinition Width="10"/>
                        </Grid.ColumnDefinitions>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="30"/>
                            <RowDefinition Height="80"/>
                            <RowDefinition Height="Auto"/>
                            <RowDefinition Height="5"/>
                        </Grid.RowDefinitions>

                        <BoxView Grid.ColumnSpan="4" Grid.RowSpan="4" BackgroundColor="{StaticResource grayDark}"/>
                        <controls:CircleImage Grid.Column="1" Grid.Row="1" HorizontalOptions="Start" VerticalOptions="End" Source="{Binding ProfileImageUrl}" WidthRequest="75" HeightRequest="75"/>
                        <Label Grid.Column="1" Grid.Row="2" Text="{Binding FullName}"/>
                        <ActivityIndicator Grid.Column="2" Grid.Row="2" IsVisible="{Binding IsBusy}" IsRunning="{Binding IsBusy}" Color="White" WidthRequest="20" HeightRequest="20" VerticalOptions="Center" />

                    </Grid>
                </DataTemplate>
            </ListView.HeaderTemplate>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Orientation="Horizontal" >
                            <StackLayout.Padding>
                                <OnPlatform x:TypeArguments="Thickness" Android="15,15,15,15" iOS="25,12,15,12" />
                            </StackLayout.Padding>
                            <Image Source="{Binding Icon}" VerticalOptions="Center" WidthRequest="20" HeightRequest="20"/>
                            <Image WidthRequest="20"/>
                            <Label Text="{Binding Label}" VerticalOptions="Center" TextColor="{Binding LabelColor}" Style="{DynamicResource ListItemTextStyle}"/>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>
</ContentPage>
```
Markup of only page that does work (note, no bindings anywhere):

```
<?xml version="1.0" encoding="utf-8" ?>
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Prepify.App.Pages.Root"
    xmlns:pages="clr-namespace:Prepify.App.Pages;assembly=Prepify.App"
    MasterBehavior="Popover"
    Title="Make Preparedness Easy">

    <MasterDetailPage.Master>
        <pages:MainMenu/>
    </MasterDetailPage.Master>

</MasterDetailPage>
```
I'm using
Visual Studio 2015
Xamarin.Forms 2.3.3.193 
Xamarin.VS 4.3.0.784

**Comment by abhishekbhalani** [comment]
@brittonbeckham  Is it worked for you? I am getting same error on My VS2017 with xamarin forms.
value can not be null on every Xaml content page.

Did you get solution?

**Comment by brittonbeckham** [comment]
Trying updating Visual Studio... what I did to solve the issue was upgrade Xamarin, and started my project over from scratch (clean template) -- then moved my code in and slowly setup everything again.
