### ISSUE TITLE
Q: Where is there protection\validation against altering the data incorrectly?

### ISSUE THREAD

**Issue by oatsoda** [xamarin/Sport#23]
Am I right in thinking that there is no server-side validation of things like:

- Changing the Membership.CurrentRating
- Changing the Membership.League 
etc.

So if I take the client code and modify it to allow me to change these things I could bump my score up? (I appreciate that this would be very immoral and/or pathetic, but you get the point :) ).

Or am I missing somewhere these are checked?

**Comment by rob-derosa** [comment]
Hi there,

There is no real validation against changing those 2 fields but you could add some protection around that on the service end. There are some examples of this where only the challenger or challengee can submit a GameResult object. I suppose you could implement something similar.

Since this was built for fun, I didn't spend a lot of time locking it down super tight.

**Comment by oatsoda** [comment]
Thanks.  I am just validating the usage of Azure Mobile Services for an enterprise-level project and wanted to be sure that some of the limitations were not going to be a problem.
