### ISSUE TITLE
Google WebView Authentication

### ISSUE THREAD

**Issue by qagwaai** [xamarin/Sport#27]
Is this going to be an issue?
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html?m=1

from above:

In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views”, such as the WebView UI element on Android and UIWebView/WKWebView on iOS, and equivalents on Windows and OS X.

**Comment by koo9** [comment]
any plan to update this app for this change?

**Comment by PhilipApptelic** [comment]
I was looking into this recently myself, so hopefully I'll save you some research here:

As discussed [here](https://forums.xamarin.com/discussion/88577/xamarin-auth-uses-webview-which-is-going-to-get-deprecated-by-google-soon) (forums) and [here](https://xamarinchat.slack.com/messages/C4TD1NHPT) (Slack), the new `customtabs` (Android) and `SFSafariViewController` (iOS) auth views are supported in [this branch](https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch) of the Xamarin.Auth library, which you can get via Nuget [here](https://www.nuget.org/packages/Xamarin.Auth/1.5.0-alpha-11).

Note that the above version of Xamarin.Auth is still an alpha pre-release!

The author, [moljac](https://github.com/moljac), has also provided samples [here](https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences).

**Comment by rob-derosa** [comment]
This project uses Azure Mobile Services for authentication so I am at the mercy of an SDK update. For now, I've implemented a hacky workaround for iOS that I will be posting very soon.

**Comment by rob-derosa** [comment]
Posted

**Comment by PhilipApptelic** [comment]
Thanks for the update, Rob. I see the user agent string hack in iOS/AppDelegate.cs, but I can't see any equivalent on the Android side - is that not necessary?

**Comment by rob-derosa** [comment]
I have not found an update for Android yet. Even the iOS workaround isn't working across the board. I will need to rewrite the entire authentication stack to get around the limitation posed by Google. This is on my plate but I may not have a solution for a few weeks.

**Comment by PhilipApptelic** [comment]
Bummer. So is it not possible to use the current prototype branch of Xamarin.Auth against the Azure Mobile Services auth back end, as linked in my [comment above](https://github.com/xamarin/Sport/issues/27#issuecomment-298976532)?

[That branch](https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch) supports Android `customtabs` and iOS `SFSafariViewController`, but I expect you already know about it so there must be some reason it can't be used :-(

**Comment by rob-derosa** [comment]
I'm evaluating a few different libs right, including Google's native SDK for authentication, then will exchange that access token for an Azure auth token... stay tuned.

**Comment by qagwaai** [comment]
Are you considering https://www.nuget.org/packages/Xamarin.Auth/1.5.0-alpha-15 as one of your options?

**Comment by TheRealDuckboy** [comment]
That's the one I was referring to above. The author seems to have implemented the `customtabs` and `SFSafariViewController` views for handling the new Google requirement.

Rob, are you not able to use that branch / alpha of **Xamarin.Auth** due to a complication with the fact that you're using the Azure auth back end rather than a stand-alone OAuth / OpenID Connect service? (I thought Azure auth offered that anyway, but I could be wrong!)

**Comment by rob-derosa** [comment]
I will most likely be using SimpleAuth, developed by my good friend and colleague, James Clancey: https://github.com/Clancey/SimpleAuth

It has a ton of providers, simplistic API, auto-handles authentication/refresh/etc

Open to other options but this one is leading the pack.

**Comment by qagwaai** [comment]
Rob - any chance to see/contribute to a branch?

**Comment by rob-derosa** [comment]
This is being actively worked on... daily. I'll be pushing code once it's working properly.

**Comment by rob-derosa** [comment]
Code has been pushed to support the latest Google OAuth requirements (SFSafariViewController on iOS and CustomTabs on Android). Please let me know if you run into issues. This was a beast trying to get everything to work again.

**Comment by TheRealDuckboy** [comment]
Great news, thanks Rob. This is a brilliant sample app and it's good to see it being kept up to date.

**Comment by PhilipApptelic** [comment]
Hey Rob, can you explain what the 'magic' is between SimpleAuth, Google OAuth2 and having to sign the app from the _keystore_ you provide in the Android Resources/Security directory in the project? (Or perhaps provide an RTFM link for those of us who have missed this in our Android education!)

The SimpleAuth [Read Me](https://github.com/Clancey/SimpleAuth/blob/master/README.md) mentions:

> - Create an OAuth Android app: [Link](https://console.developers.google.com/apis/credentials)
> > > Sign your app using the same Keystore

But it doesn't explain what this means or how it works.

Cheers,
Philip

P.S. Thanks for updating just now to fix the Android project file reference to the keystore file. I had just figured this out myself, but glad to know I got it right!

**Comment by rob-derosa** [comment]
If you just want to run the sample, everything should be included in the project (keystore, ClientIDs, etc). If you want to integrate w/ your own Google ClientID's and Azure instance, here is how I did it:

Google now requires you to use CustomTabs to select the Google profile and authenticate using their Google Auth SDK. In the Google Console API, you need to generate an iOS App, Android App and a WebApp (for the backend Azure server). To get the Client ID of the Android App, you need to use keytool to generate a SHA1 based on the keystore you plan to sign it with.

I have provided a generic one for you in `Sport.Mobile.Droid/Resources/Security/androiddebugkey.keystore`
* alias: `androiddebugkey`
* password: `android`

Google will use that Android App on their end to validate the app so you need to sign the app with the keystore every time you want to use Google Authentication on Android. In Visual Studio for Mac, there is a form you can complete in Android project options > Build > Android Package Signing so that your debug builds get signed too. This form doesn't exist in Visual Studio 2017 but if the build tasks are in the .csproj, it will try to sign it during a deploy to device.

**Comment by qagwaai** [comment]
Rob - thank you! is the signing process documented somewhere?

**Comment by rob-derosa** [comment]
I will add the previous comment to the README
