### ISSUE TITLE
Update Xamarin.Sport to use new version of Azure Mobile Services (now Mobile Client)

### ISSUE THREAD

**Issue by ltaljaard** [xamarin/Sport#7]
This sample still uses package WindowsAzure.MobileServices version 1.3.2. A stable new version has now been released. The NuGet package is now called Azure Mobile Client SDK, version 2.0.1. The login flow (and backend code) is different for the new version. Kindly update the Sport sample.

**Comment by rob-derosa** [comment]
Will look into this - thanks for reporting.

**Comment by denisz1** [comment]
:+1:

**Comment by Amplicade** [comment]
Is there any update on this available? The "old" portal will be migrated to the "new" one soon, expect this to be a breaking change in the backend.

**Comment by rob-derosa** [comment]
This task is in-progress. It will be using Azure App Services moving forward.

**Comment by Amplicade** [comment]
Any timeline available maybe?

**Comment by rob-derosa** [comment]
I'm hoping in a few weeks. The project is undergoing about 15 different updates to make it current and relevant, migrating to App Services being one of them. Of those 15, I need to implement 5 or 6 before I can post source code that has zero regressions.

I work on this project in my spare time - of which I haven't had much. I will make it available as soon as the app is functionally sound. Thanks for your patience.

**Comment by rob-derosa** [comment]
I'm posting a very early build of Sport v2 that connects to Azure App Services and uses the latest of all libraries/SDKs. I have not done a super thorough job of testing yet so please keep that in mind but I wanted to get you guys some bits ASAP.

This includes a lot of changes to both the front and back ends.

Changes include:
- Updated to Forms 2.3
- Azure App Service support
- Converted to use PCL instead of Shared Projects
- Local data store now uses Azure Offline Sync
- Other various updates to support the latest from 3rd party frameworks/libs

https://www.dropbox.com/s/o2jeeq1ioowlrhh/Xamarin%20Sport2.0.zip?dl=0

**Comment by rob-derosa** [comment]
Latest code pushed.
